import { Toaster } from "@/components/ui/sonner";
import SessionProviderWrapper from "@/providers/SessionProviderWrapper";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SessionProviderWrapper>{children}</SessionProviderWrapper>
        <Toaster position="top-right" richColors />
      </body>
    </html>
  );
}
